name: Run autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: "Select tests to run"
        required: true
        type: choice
        default: all
        options:
          - all
          # Можно добавить другие варианты, например:
          # - smoke
          # - regression

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Python Tests
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          if [ "${{ github.event.inputs.deployment_target }}" == "all" ]; then
            pytest
          else
            pytest tests/${{ github.event.inputs.deployment_target }}
          fi
